name: CI

on:
- push
- pull_request

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install -y meson ninja-build
    - uses: actions/checkout@v4
    - run: meson setup build
    - run: ninja -C build
    - run: sudo ninja -C build install
    - run: nanoidgen
